var d=null;Array.prototype.remove=function(a,b){var c=this.slice((b||a)+1||this.length);this.length=a<0?this.length+a:a;return this.push.apply(this,c)};
$(document).ya(function(){var a={G:60,P:10,n:600,g:300,f:400,Q:10,H:15,c:[],a:d,w:0,N:0,O:0,s:0,D:0,q:0,u:0,j:!1,V:function(a){$("#debug").text(a)},k:0,Fa:0,scale:1,t:!1,o:!1,A:!1,h:"test"};a.ja=$("#canvas").la().left;a.ka=$("#canvas").la().top;a.R=[];a.R=function(){};a.e=function(b){var c;if(b)for(c in b)b.hasOwnProperty(c)&&(this[c]=b[c]);else this.text="",this.color="#000",this.Aa=this.d=20,this.x=a.g/2,this.y=a.f};a.e.prototype.contains=function(a){return this.I(a)<this.d*this.d};a.e.prototype.I=
function(b){var c=this.x-a.x(b),b=this.y-a.y(b);return c*c+b*b};a.e.prototype.getDate=function(){return a.F(this.y)};a.e.prototype.r=function(){a.b.fillStyle=this.color;a.window.W(this);if(a.a==this)a.b.strokeStyle="#F00",a.window.X(this);a.b.fillStyle="#FFF";a.b.fillText(this.d/5<this.text.length?this.text.substring(0,this.d/5)+"...":this.text,this.x,this.y)};a.M=function(b){a.a=b;$("#rightpanel").K("hidden")};a.i=function(){a.a=d;$("#rightpanel").l("hidden");$("#timetextbox").l("hidden")};a.ma=
function(b){if(a.a===b)a.a=d;a.c.remove(a.c.indexOf(b))};a.x=function(b){return b.pageX-a.ja};a.y=function(b){return b.pageY-a.ka};a.Ca=function(a){return a.getTime()-Date.now()};a.Y=function(){var b;a.b.save();b=new Date(Date.now());a.b.strokeStyle="#F88";y=a.m(b);a.b.beginPath();a.b.moveTo(0,y);a.b.lineTo(a.g,y);a.b.lineWidth=2;a.b.stroke();b=new Date(a.F(a.n));b.setHours(0);b.setMinutes(0);b.setSeconds(0);a.b.fillStyle="#000";a.b.textAlign="left";for(a.b.lineWidth=1;a.m(b)>0;){a.b.strokeStyle=
"#DDD";b=new Date(b.getTime()+864E5);y=a.m(b);a.b.beginPath();a.b.moveTo(0,y);a.b.lineTo(a.g,y);if(b.getDay()===1||b.getDay()===0)a.b.strokeStyle="#88F";a.b.stroke();a.b.fillText(a.p(a.F(y)),10,y-5)}a.b.restore()};a.ia="jan,feb,mar,apr,may,june,july,aug,sep,oct,nov,dec".split(",");a.U="sun,mon,tue,wed,thu,fri,sat".split(",");a.Da=function(){};a.Ea=function(){};a.F=function(b){return new Date((a.f-b)*2E6+Date.now())};a.m=function(b){return a.f-(b.getTime()-Date.now())/2E6};a.p=function(b){return a.U[b.getDay()]+
" "+a.ia[b.getMonth()]+" "+b.getDate()};a.z=function(a){return a.getHours()+":"+(a.getMinutes()<10?"0"+a.getMinutes():a.getMinutes())};a.qa=function(b){var c;a.D=0;a.q=0;a.u=0;if(!(Math.abs(b)<6E4)){b>0||(b*=-1);if(b>6048E8)c=Math.floor(b/6048E8),b-=6048E8*c,a.D=c;if(b>864E5)c=Math.floor(b/864E5),b-=864E5*c,a.q=c;if(b>36E5)c=Math.floor(b/36E5),a.u=c}};a.window={};a.window.clear=function(){a.b.clearRect(0,0,a.g,a.n)};a.window.W=function(b){a.b.beginPath();a.b.arc(b.x,b.y,b.d,0,360,!1);a.b.fill()};
a.window.X=function(b){a.b.beginPath();a.b.arc(b.x,b.y,b.d,0,360,!1);a.b.stroke()};a.$=function(b){var c,e=999999999,f,g;a.i();for(c=0;c<a.c.length;c++)f=a.c[c].I(b),f<e&&(e=f,g=a.c[c]);a.M(g)};a.J=function(){var b;a.window.clear();a.Y();for(b=0;b<a.c.length;b++)a.c[b].r();a.a!==d&&a.a.r()};a.ha=function(){a.b=document.getElementById("canvas").getContext("2d");a.b.textAlign="center";a.b.textBaseline="middle";a.b.lineWidth="3";a.c=[new a.e,new a.e];a.i();a.update()};a.ea=function(b){var c,e;if(a.j)if(a.a){a.a.x=
a.x(b)-a.N;a.a.y=a.y(b)-a.O;if(Math.abs(a.a.y-a.w)<a.Q)a.a.y=a.w;a.B()}else{c=a.s-a.y(b);a.s=a.y(b);a.f-=c;for(e=0;e<a.c.length;e++)a.c[e].y-=c}a.k=a.y(b)<a.H?1:a.y(b)>a.n-a.H?-1:0};a.ga=function(){a.j=!1;a.t=!1};a.da=function(b){a.s=a.y(b);a.j=!0;a.$(b);if(a.a&&a.a.contains(b))a.N=a.x(b)-a.a.x,a.O=a.y(b)-a.a.y,a.w=a.a.y;else{a.i();if(a.o)a.M(new a.e),a.c[a.c.length]=a.a,a.t=!0,a.a.x=a.x(b),a.a.y=a.y(b),a.a.d=10,a.o=!1;a.B()}};a.update=function(){a.J();a.j&&a.t&&a.a!==d&&a.a.d<a.G&&(a.a.d+=0.5);if(a.k!==
0){a.f+=a.k;for(var b=0;b<a.c.length;b++)a.c[b].y+=a.k}return setTimeout(a.update,10)};a.B=function(){var b;a.a!==d&&(b=a.a.getDate(),$("#duedate").text(a.p(b)),$("#duetime").text(a.z(b)),a.qa(b.getTime()-Date.now()),$("#weekdisplay").text(a.D),$("#daydisplay").text(a.q),$("#hourdisplay").text(a.u),$("#text").text(a.a.text))};a.ca=function(b){var c=String.fromCharCode(b.which);if(a.A)b.which===13&&a.L();else if(b.which===13)a.i();else if(a.a!=d)c=="\u0008"?a.a.text=a.a.text.substring(0,a.a.text.length-
1):a.a.text+=c,a.B(),a.a.r()};a.fa=function(){a.k=0};a.ba=function(){a.a!==d&&a.a.d<a.G&&(a.a.d+=5)};a.pa=function(){a.a!==d&&a.a.d>a.P&&(a.a.d-=5)};a.S=function(){a.o=!0;a.i()};a.na=function(){a.a!=d&&a.ma(a.a)};a.T=function(){a.A=!0;$("#timetextbox").K("hidden");$("#timetextbox").C($("#duetime").text());$("#timetextbox").focus()};a.L=function(){var b,c;a.A=!1;$("#timetextbox").l("hidden");if(a.a!==d&&(b=Date.parse("Jan 1 "+$("#timetextbox").C()+", 2013"),!isNaN(b)))b=new Date(b),c=a.a.getDate(),
c.setHours(b.getHours()),c.setMinutes(b.getMinutes()),c.setSeconds(b.getSeconds()),a.a.y=a.m(c),$("#duetime").text(a.z(c))};a.save=function(){$.xa("storeStuff.php",{h:a.h,list:JSON.stringify(a.c),za:a.f},function(){var b=new Date(Date.now());$("#lastsaved").text("last saved "+a.z(b)+" "+a.p(b))})};a.load=function(){var b,c,e;$.get("getStuff.php",{h:a.h},function(f){a.V(unescape(f.replace(/\\\"/g,'"')));if(f.length>4){a.c=[];c=JSON.parse(unescape(f.replace(/\\\"/g,'"')));e=c[0];insettings=c[1];a.f=
insettings;a.i();for(b=0;b<e.length;b++)a.c[b]=new a.e(e[b]);a.J()}else alert("no saved calendar found")});a.b.fillText("loading...",a.g/2,a.g/2)};a.Ba=function(){$("#calnametextbox").l("hidden");a.h=$("#calnametextbox").C();a.load();a.ra=!1};a.sa=function(){$("#calnametextbox").K("hidden");a.ra=!0};a.oa=function(){$("calnametextbox").l("hidden");$("calnametextbox").C(a.h)};a.v=function(b){return this.Z=function(){if(a.a!=d)a.a.color=b}};a.ha();$("#calnametextbox").aa(a.oa);$("#loadcal").click(a.load);
$("#savecal").click(a.save);$("#canvas").ua(a.ea);$("#canvas").wa(a.ga);$("#canvas").j(a.da);$("#canvas").va(a.fa);$(document).ta(a.ca);$("#timetextbox").aa(a.L);$("#grow").click(a.ba);$("#shrink").click(a.pa);$("#addnew").click(a.S);$("#remove").click(a.na);$("#duetime").click(a.T);$("#bluebutton").click(a.v("#28C"));$("#redbutton").click(a.v("#B00"));$("#blackbutton").click(a.v("#000"))});